apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-deploy
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: commandservice
  template: 
    metadata:
      labels:
        app: commandservice
    spec: 
      containers:
        - name: commandservice
          # image: your-registry-user/commandservice:latest
          image: {your-docke-ruser}/commandservice
          ports:
          - containerPort: 8080
          env: 
            - name: RabbitMQHost
              value: rabbitmq-service
            - name: RabbitMQPort
              value: "5672"
            - name: GrpcPlatform
              value: http://platforms-clusterip:666
---
apiVersion: v1
kind: Service
metadata: 
  name: commands-clusterip
spec: 
  type: ClusterIP
  selector: 
    app: commandservice
  ports:
  - name: commandservice
    protocol: TCP
    port: 8080
    targetPort: 8080