apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx  # <--- ADD THIS LINE
  rules:
    - host: platforms.micro.com
      http:
        paths:
          - path: /api/platforms
            pathType: Prefix
            backend:
              service:
                name: platforms-clusterip
                port:
                  number: 8080
          - path: /api/c/platforms
            pathType: Prefix
            backend:
              service:
                name: commands-clusterip
                port:
                  number: 8080