apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-deploy
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: platformservice
  template: 
    metadata:
      labels:
        app: platformservice
    spec: 
      containers:
        - name: platformservice
          # image: your-registry-user/platformservice:latest
          image: {your-docke-ruser}/platformservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secrets
                  key: SA_PASSWORD
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: RabbitMQHost
              value: "rabbitmq-service"
            - name: RabbitMQPort
              value: "5672"
            - name: ConnectionStrings__PlatformsConn
              value: "Server=sqlserver-service;Initial Catalog=platformsdb;User ID=sa;Password=$(DB_PASSWORD);TrustServerCertificate=True;"
            - name: CommandService
              value: http://commands-clusterip:8080/api/c/platforms
            - name: Kestrel__Endpoints__Grpc__Protocols
              value: Http2
            - name: Kestrel__Endpoints__Grpc__Url
              value: http://platforms-clusterip:666
            - name: Kestrel__Endpoints__webApi__Protocols
              value: Http1
            - name: Kestrel__Endpoints__webApi__Url
              value: http://platforms-clusterip:8080
---
apiVersion: v1
kind: Service
metadata: 
  name: platforms-clusterip
spec: 
  type: ClusterIP
  selector: 
    app: platformservice
  ports:
  - name: platformservice
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: platformgrpc
    protocol: TCP
    port: 666
    targetPort: 666