apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sqlserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          # image: mcr.microsoft.com/mssql/server:2022
          image: mcr.microsoft.com/azure-sql-edge ## Use this if running on arm64
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlserver-secrets
                key: SA_PASSWORD
          volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: sqlserverdb
      volumes:
      - name: sqlserverdb
        persistentVolumeClaim:
          claimName: sqlserver-claim
---
apiVersion: v1
kind: Service
metadata: 
  name: sqlserver-service # This is the "Server=" name in your API connection string
spec: 
  type: ClusterIP
  selector: 
    app: sqlserver
  ports:
  - name: sqlserver
    protocol: TCP
    port: 1433
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata: 
  name: sqlserver-loadbalancer
spec: 
  type: LoadBalancer
  selector: 
    app: sqlserver
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433