apiVersion: v1
kind: Secret
metadata:
    name: sqlserver-secrets
type: Opaque
data:
    # Values must be Base64 encoded. In this case is "YourPassword123" Base64 encoded.
    SA_PASSWORD: WW91clBhc3N3b3JkMTIz
