apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-deployment
  labels:
    {{- include "micro.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.commands.replicaCount }}
  selector:
    matchLabels:
      app: commands
  template:
    metadata:
      labels:
        app: commands
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: commands
          image: {{ .Values.commands.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.commands.containerPort }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: RabbitMQHost
              value: "{{ default "platform-rabbitmq" .Values.rabbitmq.host }}"
            - name: GrpcPlatform
              value: "http://platforms-service:666"
