apiVersion: v1
kind: Service
metadata:
  name: commands-service
  labels:
    {{- include "micro.labels" . | nindent 4 }}
spec:
  selector:
    app: commands
  ports:
    - protocol: TCP
      port: {{ .Values.commands.service.port }}
      targetPort: {{ .Values.commands.containerPort }}
  type: ClusterIP
