apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-deployment
  labels:
    {{- include "micro.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.platform.replicaCount }}
  selector:
    matchLabels:
      app: platforms
  template:
    metadata:
      labels:
        app: platforms
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: platform
          image: {{ .Values.platform.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.platform.containerPort }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: RabbitMQHost
              value: "{{ default "platform-rabbitmq" .Values.rabbitmq.host }}"
            - name: ConnectionStrings__PlatformsConn
              value: "Server=platform-sqlserver;Initial Catalog={{ .Values.mssql.database }};User ID=sa;Password={{ .Values.mssql.saPassword }};TrustServerCertificate=True;"
