apiVersion: v1
kind: Service
metadata:
  name: platforms-service
  labels:
    {{- include "micro.labels" . | nindent 4 }}
spec:
  selector:
    app: platforms
  ports:
    - protocol: TCP
      port: {{ .Values.platform.service.port }}
      targetPort: {{ .Values.platform.containerPort }}
  type: ClusterIP
