apiVersion: v1
kind: Service
metadata:
  name: load-balancer-test
  annotations:
    k44sServiceType: HTTP
    k44sSslEnabled: "True"
  labels:
    app: hello-balancer
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
  - port: 443
    name: https
    protocol: TCP
  selector:
    app: hello-balancer
  type: LoadBalancer